Repository johnb9682/tpcc-soccer-manager-app, pull requests merged in 2021-08, with the labels that each got.

#10 songyu/eventHome - add event home screen (UI)
  App.js
  src/components/Button/index.js
  src/components/Button/style.js
  src/components/Heading/index.js
  src/components/Input/index.js
  src/components/Input/style.js
  src/components/NavBar/index.js
  src/components/NavBar/styles.js
  src/components/NoData/index.js
  src/components/NoData/style.js
  src/components/RoundRectContainer/index.js
  src/components/RoundRectContainer/style.js
  src/components/SearchInput/index.js
  src/components/SearchInput/style.js
  src/components/constants.js
  src/components/index.js
  src/components/theme.js
  src/screens/AccountScreens/RegisterScreen/index.js
  src/screens/AccountScreens/RegisterScreen/style.js
  src/screens/EventScreens/EventHomeScreen/index.js
  src/screens/EventScreens/EventHomeScreen/style.js
  src/screens/EventScreens/components/EventItem/index.js
  src/screens/EventScreens/components/EventItem/style.js
  src/screens/EventScreens/components/EventSection/index.js
  src/screens/EventScreens/components/EventSection/style.js
  src/screens/EventScreens/components/constants.js
  src/screens/LandingScreen/index.js
  src/screens/LandingScreen/style.js
  src/shared/zustand/event/index.js
  src/shared/zustand/event/mockData.js
Labels: enhancement, new feature

#11 songyu/loginDI - add login data integration
  App.js
  src/components/Input/index.js
  src/components/Loading/index.js
  src/components/Loading/style.js
  src/screens/AccountScreens/RegisterScreen/index.js
  src/screens/LandingScreen/index.js
  src/screens/LandingScreen/style.js
  src/shared/api/auth/index.js
  src/shared/zustand/auth/index.js
Labels: enhancement

#9 ericding/ProfileScreen - UI component for ProfileScreen and fix bug of Input component
  App.js
  src/components/Avatar/index.js
  src/components/Avatar/style.js
  src/components/Button/style.js
  src/components/Input/index.js
  src/components/Input/style.js
  src/components/theme.js
  src/screens/AccountScreens/ProfileScreen/index.js
  src/screens/AccountScreens/ProfileScreen/style.js
  src/shared/zustand/profile/index.js
  src/shared/zustand/profile/mockData.js
Labels: enhancement, fix, new feature

#13 songyu/loginFix - fix login issue cased by asyncStorage
  App.js
  src/shared/api/cache.js
  src/shared/zustand/auth/index.js
Labels: bug, fix

#15 songyu/teamHome - add team home screen
  App.js
  src/components/Avatar/index.js
  src/components/Avatar/style.js
  src/components/NavBar/index.js
  src/components/index.js
  src/screens/EventScreens/EventHomeScreen/index.js
  src/screens/TeamScreens/TeamHomeScreen/index.js
  src/screens/TeamScreens/TeamHomeScreen/style.js
  src/screens/TeamScreens/components/TeamItem/index.js
  src/screens/TeamScreens/components/TeamItem/style.js
  src/shared/zustand/event/mockData.js
  src/shared/zustand/team/index.js
  src/shared/zustand/team/mockData.js
Labels: enhancement, new feature

#14 songyu/useThemeFont - update to use enum for font sizes
  src/components/Avatar/style.js
  src/components/Button/style.js
  src/components/Heading/index.js
  src/components/NoData/style.js
  src/components/theme.js
  src/screens/AccountScreens/ProfileScreen/style.js
  src/screens/AccountScreens/RegisterScreen/style.js
  src/screens/EventScreens/EventHomeScreen/style.js
  src/screens/EventScreens/components/EventItem/style.js
  src/screens/EventScreens/components/EventSection/index.js
  src/screens/LandingScreen/style.js
Labels: cleanup

#16 fix avatar font var name
  src/components/Avatar/index.js
Labels: fix

#17 songyu/createTeamScreen - Add createTeam screen
  App.js
  src/components/Input/index.js
  src/components/Input/style.js
  src/components/theme.js
  src/screens/TeamScreens/CreateTeamScreen/index.js
  src/screens/TeamScreens/CreateTeamScreen/style.js
  src/screens/TeamScreens/TeamHomeScreen/index.js
Labels: enhancement

#19 songyu/teamScreen - Add team screen UI
  App.js
  src/components/RoundRectContainer/index.js
  src/components/theme.js
  src/screens/TeamScreens/TeamHomeScreen/index.js
  src/screens/TeamScreens/TeamHomeScreen/style.js
  src/screens/TeamScreens/TeamScreen/index.js
  src/screens/TeamScreens/TeamScreen/style.js
  src/screens/TeamScreens/components/TeamItem/index.js
  src/screens/TeamScreens/components/TeamItem/style.js
  src/screens/TeamScreens/components/TeamMemberItem/index.js
  src/screens/TeamScreens/components/TeamMemberItem/style.js
  src/shared/zustand/team/index.js
  src/shared/zustand/team/mockData.js
Labels: enhancement
